name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          timestamp=$(date --utc --rfc-3339=seconds)
          data="$(jq -e ".timestamp = \"${timestamp}\"" ./lists/websites.json)"
          echo -E "${data}" > ./lists/websites.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --message "Build website list" --message "[skip actions]"
          git push
